---
# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
# All rights reserved.

- name: Finding repository file that contains ol7_addons section
  find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
    contains: ".*ol7_addons"
    use_regex: no
  register: REPO_FILE
  failed_when: REPO_FILE.matched > 1

- name: Enabling existing Oracle Linux Addons repository
  ini_file:
    path: "{{ REPO_FILE.files|map(attribute='path')| list | join('') }}"
    section: "ol7_addons"
    option: enabled
    value: "1"
  when: REPO_FILE.matched == 1

- name: Creating Oracle Linux Addons repository
  yum_repository:
    name: ol7_addons
    description: "Oracle Linux $releasever Add ons ($basearch)"
    baseurl: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL7/addons/$basearch/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    gpgcheck: yes
    enabled: yes
    owner: root
    group: root
    mode: 0644
  when: REPO_FILE.matched == 0
