# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
# All rights reserved.

- name: Register with username and password and consume subscriptions defined by Pool ID 
  redhat_subscription:
    state: present
    username: "{{ RHN_USERNAME }}"
    password: "{{ RHN_PASSWORD }}"
#    auto_attach: true
#    pool: '^Red Hat Developer Subscription$'
    pool_ids: 
      - "{{ RHN_POOL_ID1 }}"
    force_register: no
  when: (RHN_REGISTER == "yes")